// Repository scaffolder - generates missing Copilot components

const fs = require('fs');
const path = require('path');
const RepositoryAnalyzer = require('./analyzer');
const TemplateEngine = require('./templates');

class RepositoryScaffolder {
  constructor(repoPath) {
    this.repoPath = path.resolve(repoPath);
    this.analyzer = new RepositoryAnalyzer(this.repoPath);
    this.generatedFiles = [];
    this.generatedDirs = [];
  }

  // Scaffold missing components
  scaffold() {
    const report = this.analyzer.analyze();

    if (report.isReadyForCopilot) {
      return {
        success: true,
        alreadySetup: true,
        message: 'Repository is already configured for Copilot',
        generatedFiles: [],
        generatedDirs: [],
      };
    }

    // Create missing directories
    for (const dir of report.gaps.missingDirectories) {
      this.createDirectory(dir);
    }

    // Create missing files
    for (const file of report.gaps.missingFiles) {
      this.createFile(file);
    }

    // Create optional files
    for (const file of report.gaps.missingOptionalFiles) {
      this.createFile(file, true);
    }

    return {
      success: true,
      alreadySetup: false,
      message: 'Scaffolding completed successfully',
      generatedFiles: this.generatedFiles,
      generatedDirs: this.generatedDirs,
    };
  }

  // Create directory structure
  createDirectory(dirPath) {
    const fullPath = path.join(this.repoPath, dirPath);
    
    if (!fs.existsSync(fullPath)) {
      fs.mkdirSync(fullPath, { recursive: true });
      this.generatedDirs.push(dirPath);
      
      // Create .gitkeep for empty directories
      const gitkeepPath = path.join(fullPath, '.gitkeep');
      fs.writeFileSync(gitkeepPath, '');
    }
  }

  // Create file from template
  createFile(filePath, isOptional = false) {
    const fullPath = path.join(this.repoPath, filePath);

    // Skip if file already exists
    if (fs.existsSync(fullPath)) {
      return;
    }

    // Ensure directory exists
    const dirPath = path.dirname(fullPath);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }

    let content = '';

    // Generate content based on file type
    if (filePath === 'copilot-setup-steps.yml') {
      content = TemplateEngine.generateCopilotSetupSteps();
    } else if (filePath === '.copilot/copilot.yml') {
      content = TemplateEngine.generateCopilotConfig();
    } else if (filePath === '.copilot/custom-instructions.md') {
      content = TemplateEngine.generateCustomInstructions();
    } else if (filePath === 'COPILOT_SETUP.md') {
      content = TemplateEngine.generateSetupGuide();
    } else if (filePath === '.env.example') {
      content = TemplateEngine.generateEnvExample();
    } else {
      // Default template
      content = `# ${path.basename(filePath)}\n# Auto-generated by copilot-starter-kit\n`;
    }

    // Write file
    fs.writeFileSync(fullPath, content, 'utf8');
    this.generatedFiles.push(filePath);
  }

  // Create example agent
  createExampleAgent(agentName = 'my-agent') {
    const agentPath = path.join(this.repoPath, 'agents', `${agentName}.js`);
    
    if (!fs.existsSync(path.dirname(agentPath))) {
      fs.mkdirSync(path.dirname(agentPath), { recursive: true });
    }

    if (!fs.existsSync(agentPath)) {
      const content = TemplateEngine.generateCustomAgent(agentName);
      fs.writeFileSync(agentPath, content, 'utf8');
      this.generatedFiles.push(`agents/${agentName}.js`);
    }
  }

  // Create example skill
  createExampleSkill(skillName = 'my-skill') {
    const skillPath = path.join(this.repoPath, 'skills', `${skillName}.js`);
    
    if (!fs.existsSync(path.dirname(skillPath))) {
      fs.mkdirSync(path.dirname(skillPath), { recursive: true });
    }

    if (!fs.existsSync(skillPath)) {
      const content = TemplateEngine.generateCustomSkill(skillName);
      fs.writeFileSync(skillPath, content, 'utf8');
      this.generatedFiles.push(`skills/${skillName}.js`);
    }
  }

  // Get report of scaffolding
  getReport() {
    return {
      generatedFiles: this.generatedFiles,
      generatedDirs: this.generatedDirs,
      totalGenerated: this.generatedFiles.length + this.generatedDirs.length,
    };
  }
}

module.exports = RepositoryScaffolder;
